permalink: /archives/:year/:month/:day/:title

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

safe: true
lsi: false
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: bob.ippoli.to
tagline: "Bob Ippolito (@etrepum) on Haskell, Python, Erlang, JavaScript, etc."
author:
  name: Bob Ippolito
  email: bob@redivi.com
  github: etrepum
  twitter: etrepum
services:
  google_analytics: 'UA-30504730-1'
  disqus: 'fromfutureimport'
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: 'archives'

production_url: https://bob.ippoli.to
tags_path: /tags.html
archive_path: /archive.html
categories_path: /categories.html

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13
  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change theme here if needed.
  #
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude:
  - README.md
  - default.nix
  - start-dev.sh
  - Gemfile
  - ci
  - .editorconfig
  - .travis.yml
  - .nix-gems