permalink: /archives/:year/:month/:day/:title/
encoding: utf-8

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

safe: true
lsi: false
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: bob.ippoli.to
tagline: "Bob Ippolito (@etrepum) on Haskell, Python, Erlang, JavaScript, etc."
author:
  name: Bob Ippolito
  email: bob@redivi.com
  github: etrepum
  twitter: etrepum
services:
  google_analytics: 'UA-30504730-1'
  disqus: 'fromfutureimport'
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: 'archives'

production_url: https://bob.ippoli.to

tags_path: /tags/
archive_path: /archive/
categories_path: /categories/

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude:
  - README.md
  - default.nix
  - start-dev.sh
  - Gemfile
  - ci
  - .editorconfig
  - .travis.yml
  - .nix-gems
  - scripts
  - node_modules
  - package-lock.json
  - package.json
